//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SismaV02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int CodBitac { get; set; }
        public System.DateTime FechaBitac { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Tabla { get; set; }
        public string Registro { get; set; }
        public int CodTransac { get; set; }
        public int CodUsuario { get; set; }
    
        public virtual Transaccion Transaccion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
