//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SismaV02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CobroServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CobroServicio()
        {
            this.DetalleCobro = new HashSet<DetalleCobro>();
        }
    
        public int CodCobro { get; set; }
        public decimal MontoTotal { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Glosa { get; set; }
        public int CodUsuario { get; set; }
        public int codContrato { get; set; }
        public Nullable<int> CodLectura { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Lectura Lectura { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCobro> DetalleCobro { get; set; }
    }
}
