//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SismaV02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.CobroServicio = new HashSet<CobroServicio>();
            this.EstadoServicio = new HashSet<EstadoServicio>();
        }
    
        public int CodContrato { get; set; }
        public string CodFijo { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public string DireccionNro { get; set; }
        public string NroDpto { get; set; }
        public string Observacion { get; set; }
        public int CodMedidor { get; set; }
        public int CodCalle { get; set; }
        public int CodCategoria { get; set; }
        public int CodUsuario { get; set; }
        public int CodSocio { get; set; }
    
        public virtual Calle Calle { get; set; }
        public virtual CatServicio CatServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CobroServicio> CobroServicio { get; set; }
        public virtual Medidor Medidor { get; set; }
        public virtual Socio Socio { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadoServicio> EstadoServicio { get; set; }
    }
}
