//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SismaV02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoServicio
    {
        public int CodEstado { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Estado { get; set; }
        public int CodContrato { get; set; }
    
        public virtual Contrato Contrato { get; set; }
    }
}
