//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SismaV02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lectura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lectura()
        {
            this.CobroServicio = new HashSet<CobroServicio>();
        }
    
        public int CodLectura { get; set; }
        public int ValorLectura { get; set; }
        public int Estado { get; set; }
        public System.DateTime Fecha { get; set; }
        public int CodMedidor { get; set; }
        public int CodPeriodo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CobroServicio> CobroServicio { get; set; }
        public virtual Medidor Medidor { get; set; }
        public virtual Periodo Periodo { get; set; }
    }
}
